# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZGVIP_code', models.CharField(max_length=50, verbose_name='足购id')),
                ('name', models.CharField(max_length=40, verbose_name='商家名称')),
                ('enter_time', models.DateTimeField(auto_now_add=True)),
                ('out_money', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='入库金额')),
            ],
            options={
                'db_table': 'tb_deposit_out',
            },
        ),
        migrations.CreateModel(
            name='MerchantManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=40, verbose_name='商家名称')),
                ('memo', models.CharField(max_length=200, verbose_name='备忘录')),
                ('amount_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='商家所剩余额')),
                ('ZGVIP_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.User', to_field='ZGVIP_code', verbose_name='外键足购id')),
            ],
            options={
                'db_table': 'tb_merchant_manage',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(max_length=200, verbose_name='图片名称'),
        ),
    ]
