# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200115_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='wx_username',
            field=models.CharField(default='', max_length=80, verbose_name='提现微信名称'),
        ),
    ]
