# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200116_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranksell',
            name='ladder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Ladder', verbose_name='外键字段(阶梯)'),
        ),
    ]
