# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200119_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='commentary',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备注'),
        ),
    ]
