# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_merchant_commentary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPostage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', models.CharField(max_length=200, verbose_name='配送区域')),
                ('initial_money', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='首件价格')),
                ('more_money', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='续件价格')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.FreightManage', verbose_name='模板外键')),
            ],
            options={
                'db_table': 'tb_city_postage',
            },
        ),
    ]
