# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-30 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20200317_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.IntegerField(default=0, verbose_name='当天订单总量')),
                ('run_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当天营业额')),
                ('refund_count', models.IntegerField(default=0, verbose_name='当天退款单量')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当天退款总额')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'db_table': 'tb_run_data',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('address', models.CharField(max_length=50, verbose_name='退货地址')),
                ('detail', models.CharField(max_length=50, verbose_name='详细街道')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
            ],
            options={
                'db_table': 'tb_sales_return',
            },
        ),
        migrations.RenameField(
            model_name='citypostage',
            old_name='initial_price',
            new_name='initial_money',
        ),
        migrations.RenameField(
            model_name='citypostage',
            old_name='more_price',
            new_name='more_money',
        ),
    ]
