# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-22 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20200522_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='跳转的url'),
        ),
    ]
