# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-26 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_auto_20200526_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='角色名称'),
        ),
    ]
