# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_administrator_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Role', verbose_name='外键关联角色表'),
        ),
    ]
