# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-27 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_auto_20200526_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150, verbose_name='选择状态')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Role', verbose_name='角色外键')),
            ],
            options={
                'db_table': 'tb_select_resource',
            },
        ),
    ]
