# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_selectresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectresource',
            name='role_id',
            field=models.IntegerField(verbose_name='角色外键'),
        ),
    ]
